---
- name: "Services | Reload postfix"
  ansible.builtin.systemd_service:
    name: postfix
    state: reloaded
  become: true

- name: "Services | Reload sysctl"
  ansible.builtin.command: sysctl --system  # noqa: command-instead-of-module
  changed_when: false
  become: true
